is_debug: true
listen:
  type: port
  port: 8081
storage:
  host: 127.0.0.1
  port: 5432
  database: test_crud
  username: postgres
  password: 1234
  pg_pool_max_conn: 10
jwt_key: normalnybol!!!
socket_jwt_key: normalnybol!!!
app_version: 0.0.1
max_file_size: 10485760
public_path: /../../public
